
#print 40x

print("hello world")
print("i love to study in GOA")
print("i really needed this place")
print("so my mom told me about it")
print("and i thought that this was gonna be very very very interesting")
print("and i always wanted to learn programming ")
print("so i choosed this proffesion for entire of my life")
print("i will not gonna change this proffesion")
print("cause i think that i can learn this and earn more money")
print("but money is not important to me at this moment")
print("because only what i need is to learn programming")
print("and i think i can it")
print(" i am  " + str ( 12 )  +  " years old ")
print("i was always playing video games")
print("but , when i heared that i can learn and play at the same time , i registred in GOA")
print("i think this academy is the best academy in the world")
print("i need to start working when i will be 14-15 years old")
print("soo i think that after i can do my favourite proffesion and make money also")
print("i love reading books ")
print("and i think that man who gave us book is very clever man")
print("he was also thinking about future")
print("and if books were not here at this moment i will not gonna be able to write in english")
print("i have huge love about programming ")
print("I THINK THAT THIS IS ACADEMY WHERE YOU CAN MAKE YOURSELVES BETTER AND BETTER")
print("i wanted to be in this academy for 3 years")
print("and finally im here")
print("when i told my parents about it they sayed:")
print("NO PROBLEM")
print("and thanks for my parents that im here and learning this proffesion")
print("i think it is gonna be harder than i think but")
print("never ever give up for your dreams")
print("and this is my dream")
print("i sayed something about myfelf and i think that you will understand how much this is for me")
print("my parents always needed to not play a videogames")
print("and yesterday i told them that i deleted all the games")
print("they were very happy")
print("they were always saying")
print("if you play here every day , every night")
print("you will not gonna be able to do somthing in your life")
print("thank you for reading,IM OUT")


#math operations 

#first is (+)

print( 20 + 26 )
print( 60 + 232 )
print( 97 + 67 )
print( 302 + 23 )
print( 95 + 59 )
print( 64 + 88 )
print( 87 + 88 )
print( 974 + 636 )
print( 65 + 76)
print( 56 + 9 )

#end of (+) 

#starting (-)

print( 78 - 45 )
print( 90 - 89 )
print( 79 - 71 )
print( 88 - 76 )
print( 576 - 354 )
print( 467 - 456 )
print( 875 - 556 )
print( 465 -235 )
print( 678 - 678 )
print(776 - 564)

#end of (-)


#starting (*)

print( 866 * 4 )
print( 88 * 7)
print( 66 * 5 )
print( 64 * 4 )
print( 453 * 77)
print( 555 * 555)
print( 453 * 4 )
print( 66 * 6 )
print( 66 *3 )
print( 456 * 6 )

#end of (*)

#starting (/)

print( 32 / 8 )
print(2323 / 98)
print(7866 / 8)
print( 363 / 7 )
print( 2636 / 3 )
print( 636 / 7 )
print( 639 / 3 )
print( 323 / 8)
print( 865 / 3)
print( 775 / 8 )

#end of (/)

#starting (//)

print( 3535 // 3 )
print( 3746 // 4 )
print( 5637 // 3 )
print( 766 // 8)
print( 786 // 87)
print( 8966 // 8 )
print( 87676 // 8767 )
print( 767 // 564 )
print( 875 // 8 )
print( 646 // 8 )

#end of whole homework